# @package _group_
data_root_dir: /home/andre/Desktop/lama-new/dataTrain
out_root_dir: /home/andre/Desktop/lama-new/experiments
tb_dir: /home/andre/Desktop/lama-new/tb_logs
pretrained_models: /home/andre/Desktop/lama-new/
